version: '3'

services:

  web:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - "./public:/var/www/html"
      - "./docker/php/log:/var/log"
      - "./docker/php/php.ini:/usr/local/etc/php/php.ini"
      - "./docker/php/app.conf:/usr/local/etc/php/conf.d/app.conf"

  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345
    volumes:
      - "db:/var/lib/mysql"
volumes:
  db: